### ISSUE TITLE
MQTT connection

### ISSUE THREAD

**Issue by kimoudev** [iot-makers/sigfox-platform#1]
Hi @AntoinedeChassey 

if I understand well this schema does not work with sigfox-platform
1-Create device
2-Create MQTT subscribe in sigfox-platform.
3-Mqtt client send message to broker with Device(1) token
4-Persistence message in mongodb

Thank you.
Joachim

Hi,

FYI, the repo moved here: https://github.com/IoT-Makers/sigfox-platform

When adding an MQTT connector, you can create an alert on a device of your choice that will push data to this new connector.

Step 1. Create a connector with type "MQTT"
Step 2. Create an alert on a device with the MQTT connector created
Step 3. Trigger the alert and the message of your choice will be sent to this connector

Best,

Antoine

**Comment by adechassey** [comment]
What are you trying to do?
Where is your MQTT broker hosted? The Sigfox Platform MQTT connector only pushes data to a custom broker.

**Comment by kimoudev** [comment]
What I'm trying to do is:
1.Take device ID / Token from mongodb
2.publish data (temparature,humidity ...etc)  from MQTT.fx client to
3.Broker (same machine with sigfox-platform)
3.sigfox-platform subscribe to broker
4.persistence message in mongod 

Please you can give some tracks to modify
the MQTT already set in order to have
1.Mqtt message input also like Sigfox message input ?

@AntoinedeChassey @luisomoreau 

Thanks

**Comment by adechassey** [comment]
Currently this is not implemented but could be part of a future evolution of the platform.
It could be a custom script at boot which connects to the broker and subscribes to the topic you define (in environment variables for instance). And stores the incomming messages in db.
Not a big deal, you can implement it and do a pull request if you wish!

**Comment by kimoudev** [comment]
Thanks you
