### ISSUE TITLE
Device list not updated after Edit

### ISSUE THREAD

**Issue by afaerber** [iot-makers/sigfox-platform#10]
**Describe the bug**
Editing the device does not appear to update the device list with changes applied. Doing a new search (by changing the search string) does show it.

**To Reproduce**
1. Go to workshop.iotagency.sigfox.com
2. Click on Devices
3. Search for a device by entering part of the id
4. Click on Edit device button
5. Select parser and category from drop-downs and enter name on right side
6. Click on Update button on lower right side
7. Compare device information in the search list still showing name empty and parser and category as None

**Expected behavior**
I would expect the Update button to trigger a refresh of the device information displayed.

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.0
 - Browser: Firefox
 - Version: 60.4.0esr

**Additional context**
ST Sigfox Munich workshop

**Comment by siyu6974** [comment]
Hi @afaerber,
Thank you for bringing this to our attention. 
Closing the issue as it is fixed with commit 964f81b  
Feel free to reopen if you still have problem with it.

**Comment by adechassey** [comment]
@all-contributors add @siyu6974 for code
