### ISSUE TITLE
Device disapears from shared devices

### ISSUE THREAD

**Issue by ghost** [iot-makers/sigfox-platform#11]
**Describe the bug**
When we share a specific device (2010C4) with our organization it disappears from the organization after a while.

**To Reproduce**
So far we only seem to have this issue with one device.

**Expected behavior**
The device should stay shared with the organization.

**Comment by ghost** [comment]
Extra note. Unsharing the category and resharing it brings it back, but only for a short time.

**Comment by adechassey** [comment]
Hello,
Thanks for noticing this bug.
It should now be fixed.
Antoine

**Comment by ghost** [comment]
Thanks!
